### ISSUE TITLE
realtime data - updating realtime candlestick bars

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#115]
I'm working out a component that can handle realtime data, after viewing [updating_data](http://rrag.github.io/react-stockcharts/documentation.html#/updating_data ) example, seemed fairly simple to just 'keep adding data to the array'

However in debug mode many console messages are printed (especially if you use multiple charts, goes to 100%) CPU, in addition every time the reducer modifies the state, all of the charts are picking up prop changes, which then triggers more console messages and so on..

1) Do you think some intensive tasks can be avoided with a simple object compare prior to doing other comparisons, or there are other unwanted side effects I am missing
```
componentWillReceiveProps(nextProps) {
          if (nextProps && (nextProps===this.props))
                return
        ...
}
```
Relevant code insde [ChartCanvas](https://github.com/rrag/react-stockcharts/blob/22fdff0298c50b690eb6a6d077f3feef92b81061/src/lib/ChartCanvas.jsx#L139-L173)

2) Any advice or experience with realtime data and react-stockcharts, (or data that updates near realtime, eg every x seconds)?

3) Also, because I am just pushing data to the end of the array, is that triggering a re-calculation on the entire array - just wondering if optimizations can be made

**Comment by rrag** [comment]
100% cpu, wow that should not happen. It might be how you have structured the components leading to repeated state updates. The `ChartCanvas` is optimized to calculate different things depending on what has changed. I cannot think of a way to optimize it further,

```
shallowEqual(nextProps, this.props)
```

will always return false, if I recall right, since `ChartCanvas` has `this.props.children` and you cannot compare `nextProps.children` and grandchildren to `this.props`. Actually in this case you need to `deepEqual` as any of the child props also could have changed. Even changing the `stroke` color of a child/grandchild will trigger a render on `ChartCanvas`, these kind of changes are considered Trivial, so you would see the console log also indicating that

Since you control when a change is made, you should control it outside of the library.

> 2) Any advice or experience with realtime data and react-stockcharts, (or data that updates near realtime, eg every x seconds)?

Nope, this is just a hobby project for me. When developing the demo, I did a lot of tests with multiple charts, and I did not have any issues. Planning to rewrite the entire demo soon, so possibly I could encounter some issues, but none right now

> 3) Also, because I am just pushing data to the end of the array, is that triggering a re-calculation on the entire array - just wondering if optimizations can be made

Are you sure calculating data is the reason for slowness? It takes no more than 25ms to complete the calculation for me, and this is only when the it is NOT a trivial change.

One possible problem you might have is likely that if you create all the calculators inside your `render`, and send them in as an array to the `calculator` it will be considered as a different `calculator[]` when comparing to `this.props` so prepare the `calculator []` outside of your `render`

Try to wrap [this](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/evaluator.js#L81-L84) with 
```
console.time("evaluation")
// line 81 to 84
console.timeEnd("evaluation")
```
While it is possible to calculate only for the newly added elements, it is just an overkill, which opens up a lot of edge cases. What if you update one of the values already present. Like you keep updating the close of the last candle.

**Comment by rrag** [comment]
@itsjimbo ?

**Comment by itsjimbo** [comment]
Sorry been really busy lately, but thanks @rrag you were correct, moving the calculators outside the any renderer helps with frequent updates, I also debounced updates (200ms) to the chart, which improved performance significantly.

**Comment by rrag** [comment]
Awesome.
