### ISSUE TITLE
Icons next to tooltip

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#165]
I have been thinking of adding support for svg next to tooltips, this can be used for icons like settings wheel, a show/hide button

I dont have a problem adding icons which are aligned to the right, 

http://plnkr.co/edit/txB1enL5KQdsa6jQao9p?p=preview

as these will be absolute positioned.

Any one has any ideas of making icons which are next to the tooltip text?

**Comment by itsjimbo** [comment]
I tried my hand at svg icons, using css you can make the icon do things on hover..
I had to render a small transparent (background) square for the mouse events to take place on the icon itself, otherwise the gaps between svg icons do not register..

http://plnkr.co/edit/DO3hyULFU6L2Bc6Mj7Dw?p=preview

When you say 'next to the tooltip text are you referring to  the OHLCTooltip info text boxes?

**Comment by rrag** [comment]
> When you say 'next to the tooltip text are you referring to the OHLCTooltip info text boxes?

yes, icons on the right can be done by simply adding svg elements to the `Chart`

The problem is svg does not have an equivalent of `float: left` so if I need an icon right next to the OHLC text, it is not possible
