### ISSUE TITLE
Zoom/padding reset after data update

### ISSUE THREAD

**Issue by yuvalkalev** [rrag/react-stockcharts#233]
Hey rrag and I wanted to congratulate on a very well written chart engine.

I recently downloaded 0.6.1 and noticed that when updating the data on the chart (candlestick), the zoom and/or padding is reset to the place where the update occured.

The updates i'm doing is either changing the last (most recent) candle or adding a new candle.
Is there a way to disable zoom/pan reset on updates?

**Comment by rrag** [comment]
check the [example](http://rrag.github.io/react-stockcharts/documentation.html#/updating_data) and the source on how to do that.

There must be some prop likely `xExtents` which gets created every time the `render()` gets called after `setState` which could lead to this behavior

**Comment by yuvalkalev** [comment]
Thank you!
It seems I was rendering a new function every new tick.

**Comment by rrag** [comment]
cool, please share what the fix was so others may benefit.

**Comment by yuvalkalev** [comment]
Well,
in my view component, I manually created the xExtends values which were passed by the container component.
This caused that every new tick that was added to the data to render the chart again (which is good), but also re-calculate the xExtends method with new extremes (the extremes were set based on the current time in UTC).
The fix was to manage the extremes on the container component in the state and pass new extremes only when important events happen (asset switched, candle size changed, etc...)

**Comment by svk31** [comment]
I'm having a similar issue where even though xExtents remain unchanged the chart gets reset on every rerender. Looking into it I found that the reason is that here: https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L902 the use of shallowEqual on an array always returns false, which again is due to this line: https://github.com/rrag/react-stockcharts/blob/master/src/lib/utils/shallowEqual.js#L44 in shallowEqual.

Since you don't check `hasOwnProperty` on `b`, only on `a`, the prototype methods `__ARRAY__` and `equals` are checked and the `!a.hasOwnProperty(key)` always returns true.

A simple fix would be to change the line in shallowEqual to read:

`if ( /* !isPrimitive(b[key]) || */(b.hasOwnProperty(key) && !a.hasOwnProperty(key)) || !isEqual(a[key], b[key])) {`

**Comment by srhtylmz19** [comment]
@yuvalkalev how did you fix the problem ? possible to share your solution ?

**Comment by horizonvert1027** [comment]
Did this issues fixed? I am still getting reset problem when adding a new candle
