### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by stanbor** [rrag/react-stockcharts#267]
Hi,

when I'm comparing http://rrag.github.io/stockcharts-demo/ with http://rrag.github.io/fullpage/documentation.html there is difference in speed. 

Besides freezing problem in fullscreen mode in SVG + Canvas in Chrome there is difference in speed when zooming in/out when you compare these two.

Why is http://rrag.github.io/stockcharts-demo/ zooming so much faster? Is it some setting that can be changed? Or is it because there is more data?

**Comment by borm** [comment]
So first reason i think it difference release version on two demo

on documentation page it is 0.6.1
on demo page - 0.2.12

**Comment by rrag** [comment]
thanks @borm you are right demo is a really old version, I have never gotten around to upgrading it to the latest.

About zoom speed, you could change it with a prop `zoomMultiplier` on `ChartCanvas` 

if you wish to 

- reverse the direction of zoom, like scroll up to zoom out (instead of zoom in) change the value to < 1
- increase the speed of zoom change to to a higher value

every zoom-in event will change the scale by `zoomMultiplier` times and zoom out will change the scale by  `1 / zoomMultiplier`

default value is - https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L945

**Comment by fxhst329** [comment]
thanks, works much better now
