### ISSUE TITLE
Min/Max zoom

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#274]
Min zoom
Not this
![3](https://cloud.githubusercontent.com/assets/4027842/26506843/905462dc-4256-11e7-9ddd-5271c41480c3.gif)
Like this
![4](https://cloud.githubusercontent.com/assets/4027842/26506849/964b7e82-4256-11e7-9ff8-284bf7b6d2d6.gif)

Max zoom
Not this
![1](https://cloud.githubusercontent.com/assets/4027842/26506855/9d354610-4256-11e7-8079-ebc0867aab15.gif)
Like this ( Note: what is free space on left and right of the chart, i mark it as red lined )
![2](https://cloud.githubusercontent.com/assets/4027842/26506865/a4a8b5da-4256-11e7-9e7f-a75d2f0380c1.gif)
And how change zoom programmatically ( I am try see how you do it in your demo, write later )?

**Comment by rrag** [comment]
firstly, there is a clamp mode, where you can do `<ChartCanvas clamp={true} ...` but that is not what you are asking though

there is https://github.com/rrag/react-stockcharts/blob/next/src/lib/scale/evaluator.js#L66

where you could change

```diff
- return arrayLength > 1 && arrayLength < showMaxThreshold(width, threshold);
+ return arrayLength > 9 && arrayLength < showMaxThreshold(width, threshold);
```

to say that there has to be a minimum of 10 points, so you cannot zoom past that. This could be made as a configurable prop (defaults to 1)

and then finally there is the gap between the right most point and the right of the chart, this is because the lib filters out all the points which dont fit inside this xDomain and shows only the `plotData`, I guess `clamp` mode might solve this for you, but I never really liked it. there are ways you could add one datapoint before and after `plotData` just to draw that, but that causes other problems, where the `yScale` domain does not include these new points added.

**Comment by borm** [comment]
`clamp={true}` that it not what i want

```
- return arrayLength > 1 && arrayLength < showMaxThreshold(width, threshold);
+ return arrayLength > 9 && arrayLength < showMaxThreshold(width, threshold);
```

it is okay, yeah, add it as a configurable prop on feature
what about min zoom? ( as second screeshot )

**Comment by rrag** [comment]
about min zoom, clamp would solve it but that also means you cannot pan beyond the edge.

alternatively you could play with the `pointsPerPxThreshold` prop in `<ChartCanvas ... pointsPerPxThreshold={1} ` and find what suits you best, default value is `2`

**Comment by piotryordanov** [comment]
I tried with:
```        
clamp={true}
pointsPerPxThreshold={40}
```

And, I still can't get to put bounds on the zoom. What did I do wrong?

**Comment by rrag** [comment]
`pointsPerPxThreshold={40}`

Default is 2, try like 0.5 or lower

**Comment by piotryordanov** [comment]
Ok. this sets the default zoom level. But, i want to stop zooming in after a specified threshold so that I have at least - for example - 5 visible candlesticks.

How can i do that?

**Comment by rrag** [comment]
I dont think it can be configured,

https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/evaluator.js#L66

try with 

```diff
- return arrayLength > 1 && arrayLength < showMaxThreshold(width, threshold);
+ return arrayLength > 5 && arrayLength < showMaxThreshold(width, threshold);
```

**Comment by piotryordanov** [comment]
So, I need to change the source code of the librar, right?

**Comment by rrag** [comment]
no no, change the source from a git clone and then run

```
$ cd /path/to/react-stockcharts
$ npm run build
```

then you could copy or link to the 

`/path/to/react-stockcharts/build` from inside your `node_modules`

once you are happy with the work send in a PR to the `master branch`

**Comment by piotryordanov** [comment]
Yeah, that's my point. It won't be configurable, so if other users want something else, they'll need to do the same :P It's fine for now, I'll skip this.

**Comment by rrag** [comment]
You are right it has to be modified to a prop of `ChartCanvas` just like `pointsPerPxThreshold` to make it configurable.
