### ISSUE TITLE
Thoughts on best practice for implementing a series of lines for entry and exit?

### ISSUE THREAD

**Issue by sourbrew** [rrag/react-stockcharts#30]
Basically want to emulate something [like this](http://content.screencast.com/users/James_Roe/folders/Jing/media/33db2a37-2d3c-4de8-bc34-74b5dc7883fe/2015-11-06_2213.png), to draw entries and exits onto a chart. I care mostly about the trend lines at the moment. I could end up having quite a few of these on a large chart, and am not sure how that would work with your auto scaling. 

Regardless your package is awesome, and I love seeing that it is in active development.

**Comment by rrag** [comment]
How are these lines drawn? interactively or via some predetermined values you have calculated some how.

If the later, it should be possible by doing that with custom components, and it will scale when the chart is pan/zoom ed

**Comment by rrag** [comment]
and one more thing, I recommend not using dashed lines, it is possible to that with svg, very easily, but on canvas, dashed lines are a pain, and involves non trivial code.

**Comment by sourbrew** [comment]
They are being determined by a parent application that is outputting them to a json feed. 

When you say custom component do you mean custom indicator or custom XXYY, it looks like i may just be able to use the [line series](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/Line.jsx) but i wasn't sure how it would handle starting and stopping and if I could run into trouble with say 300 of them added to the chart. 

I don't need the dashed lines, however could you not do something with a repeating transparent png with a dash as a pattern fill for canvas?

**Comment by sourbrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash

Also there appears to be this feature as well which looks reasonably supported.

**Comment by rrag** [comment]
Create a [custom Series](http://rrag.github.io/react-stockcharts/documentation.html#/custom_create_xxxseries), you might possibly have to use a [custom indicator](http://rrag.github.io/react-stockcharts/documentation.html#/custom_create_indicator) also to provide the details on the start and end points of different lines.

The reason I think LineSeries might now work is because it represents a continuous line. While it possible to create a discontinuous line, I have not tested that part.

Having 300 of these while technically possible, I am not too sure if that will be useful and the user be able to interpret that, looking at the chart.
