### ISSUE TITLE
Unable to add Point & Figure chart

### ISSUE THREAD

**Issue by alexandrkondrachuk** [rrag/react-stockcharts#302]
I'm trying to add Point & Figure chart but get error below :
![error_](https://user-images.githubusercontent.com/19354574/28273423-0d9377fe-6b17-11e7-81a6-8dd1d0afe608.png)
![error](https://user-images.githubusercontent.com/19354574/28273450-1a9ff846-6b17-11e7-8fbd-f8e6281b0481.png)

Here is my component:
`var { ChartCanvas, Chart, series, scale, coordinates, tooltip, axes, indicator, helper } = ReStock;

var pointAndFigureTransformOptions = { boxSize: 0.25 };

var { BarSeries, LineSeries, AreaSeries, PointAndFigureSeries } = series;
var { discontinuousTimeScaleProvider } = scale;

var { CrossHairCursor, MouseCoordinateX, MouseCoordinateY, CurrentCoordinate } = coordinates;
var { EdgeIndicator } = coordinates;

var { OHLCTooltip, MACDTooltip } = tooltip;
var { XAxis, YAxis } = axes;
var { pointAndFigure } = indicator;
var { fitWidth, TypeChooser } = helper;

class PointAndFigure extends React.Component {
	getChartCanvas() {
		return this.refs.chartCanvas;
	}
	render() {
		var { data, type, width, ratio } = this.props;
		var pAndF = pointAndFigure();

		return (
			<ChartCanvas ref="chartCanvas" ratio={ratio} width={width} height={400}
					margin={{ left: 80, right: 80, top: 10, bottom: 30 }} type={type}
					seriesName="MSFT"
					data={data} calculator={[pAndF]}
					xAccessor={d => d.date} xScaleProvider={discontinuousTimeScaleProvider}>
				<Chart id={1}
						yExtents={d => [d.high, d.low]}
						padding={{ top: 10, bottom: 20 }}>
					<XAxis axisAt="bottom" orient="bottom"/>
					<YAxis axisAt="right" orient="right" ticks={5} />
					<MouseCoordinateY
						at="left"
						orient="left"
						displayFormat={d3.format(".4s")} />

					<PointAndFigureSeries />
					<OHLCTooltip origin={[-40, 0]}/>
				</Chart>
				<Chart id={2}
						yExtents={d => d.volume}
						height={150} origin={(w, h) => [0, h - 150]}>
					<YAxis axisAt="left" orient="left" ticks={5} tickFormat={d3.format(".0s")}/>

					<MouseCoordinateX
						at="bottom"
						orient="bottom"
						displayFormat={d3.timeFormat("%Y-%m-%d")} />
					<MouseCoordinateY
						at="left"
						orient="left"
						displayFormat={d3.format(".4s")} />

					<BarSeries yAccessor={d => d.volume} fill={d => d.close > d.open ? "#6BA583" : "#FF0000"} />
				</Chart>
				<CrossHairCursor />
			</ChartCanvas>

		);
	}
}
PointAndFigure.propTypes = {
	data: React.PropTypes.array.isRequired,
	width: React.PropTypes.number.isRequired,
	ratio: React.PropTypes.number.isRequired,
	type: React.PropTypes.oneOf(["svg", "hybrid"]).isRequired,
};

PointAndFigure.defaultProps = {
	type: "svg",
};
PointAndFigure = fitWidth(PointAndFigure);`

Data array: 
![data](https://user-images.githubusercontent.com/19354574/28273473-2ae10dda-6b17-11e7-8410-18c882ff6a48.png)

By the way, I have only trouble with Point & Figure chart. Other charts (Area, Candlestick, Heikin Ashi, Renko and Kagi) work fine with such kind of data.
Hope You can help. Thanks in advance!

**Comment by rrag** [comment]
I have seen this problem earlier, I dont quite recall what the problem was, could you try changing the `boxSize` and other options?

Also could you try with the new 0.7 beta? (be sure to review the [list of breaking changes](https://github.com/rrag/react-stockcharts/issues/206))

I just created a big list of examples for 0.7 

https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/PointAndFigure

**Comment by QRMarketing** [comment]
I tried to implement Point and Figure and get this same exact bug. I notice that in the Examples the updating Point and Figure has the same issue. It seems that the big difference is that the data I am using is not day data but also hour and minute data. If any help here, here is the function and data input I am using to the chart framework (input data in the form of type string:  "2018-03-16 12:25:32"):

`function parseData() {
    
	return function(d) {
        var s = d.date.replace(/[ :]/g, "-").split("-");
        d.date = new Date( s[0], parseInt(s[1],10) - 1, s[2], s[3], s[4], s[5] );
        
		return d;
	};
}`

I feel this bug is still an issue. It would be nice to have this working.

**Comment by rrag** [comment]
@QRMarketing after the P&F is calculated what is the length of the data? I suspect this error happens when you have a data of length 1. This only happens when the ohlc data [] length is too small to begin with.

**Comment by QRMarketing** [comment]
Thanks for the response.

In review this is this same error:

TypeError: Cannot read property 'getTime' of undefined
(anonymous function)
C:/Users/blue/Desktop/PF_bptweb.1.4/bptweb/bptapp/node_modules/react-stockcharts/lib/scale/discontinuousTimeScaleProvider.js:43
  40 | 
  41 | var i = initialIndex;
  42 | var row = {
> 43 | 	date: d.getTime(),
  44 | 	startOf30Seconds: false,
  45 | 	startOfMinute: false,
  46 | 	startOf5Minutes: false,
View compiled
(anonymous function)
C:/Users/blue/Desktop/PF_bptweb.1.4/bptweb/bptapp/node_modules/react-stockcharts/lib/utils/slidingWindow.js:57
  54 | return data.map(function (d, i) {
  55 | 	// console.log(d, i);
  56 | 	if (i < skipInitial + size - 1) {
> 57 | 		return undef(sourceFunction(d), i, misc);
  58 | 	}
  59 | 	if (i >= skipInitial + size) {
  60 | 		// Treat windowData as FIFO rolling buffer
View compiled
slidingWindow
C:/Users/blue/Desktop/PF_bptweb.1.4/bptweb/bptapp/node_modules/react-stockcharts/lib/utils/slidingWindow.js:54
  51 | var accumulatorIdx = 0;
  52 | var undef = (0, _index.functor)(undefinedValue);
  53 | // console.log(skipInitial, size, data.length, windowData.length);
> 54 | return data.map(function (d, i) {
  55 | 	// console.log(d, i);
  56 | 	if (i < skipInitial + size - 1) {
  57 | 		return undef(sourceFunction(d), i, misc);

The data input is confirmed at 1000 records. I looked at the data in slidingWindow.js point and it has just one empty array item. See below:

![pf](https://user-images.githubusercontent.com/11709591/37945355-1a1761fe-3180-11e8-9616-0c21485880fa.jpg)

It is like it is not building the PF data correctly, due to some reason (see the format of data from above). Note: The other chart series all work fine and have this same data input.
