### ISSUE TITLE
Problem: Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by trevorbernard** [rrag/react-stockcharts#4]
I have jQuery as a dependency in my package.js. It appears window.$ isn't bound

**Comment by rrag** [comment]
I am assuming you are using `ChartWidthMixin` which causes this error.

I think you are right, `window.$` is not bound. Are you including jquery in the `<script ` tag?
if not, you would have to use declare `jquery` and `$` as `external` in webpack,

If you are using browserify, I would guess you need use `browserify-shim `

**Comment by trevorbernard** [comment]
jQuery is included via webpack. I `var $ = require('jquery')` in my code to access jQuery

**Comment by rrag** [comment]
There are a few options i can think of to address this problem

1. Do not use `ChartWidthMixin` I added this to remove the redundant code in the examples, I will probably remove it later since mixin usage is not recommended going forward. Instead you can define the correct `width` and `height` and pass them down to the `ChartCanvas`
2. use [webpack config](http://webpack.github.io/docs/library-and-externals.html#configuration-options) `external` to provide an alias for `jQuery` and load jQuery from html using a `<script...` tag
3. use webpack [provide plugin](http://webpack.github.io/docs/shimming-modules.html#plugin-provideplugin)

I recommend 1 above, but YMMW

**Comment by trevorbernard** [comment]
Yeah, I was just peeking at the code, and if all your doing is getting the parent reference to find its width, you don't need jquery to do that.

I'll probably just remove my usage of it as per your suggestion.

**Comment by rrag** [comment]
forgot to mention this earlier, the `ChartWidthMixin` in v0.2 branch removes the dependency of jquery

https://github.com/rrag/react-stockcharts/blob/v0.2/src/lib/helper/ChartWidthMixin.jsx

**Comment by trevorbernard** [comment]
I noticed that -- I ended up writing my own. Thanks!
