### ISSUE TITLE
use "Stateless Functional Component" where possible

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#409]
Please consider to improve/sleek the code base by using es6 with **"Stateless Functional Component"** https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc. "Stateless Functional Component" also provides better performance.

**Comment by rrag** [comment]
Thank you for sharing, it is a nice read,

although in that example listed in the article, the
```
constructor(props) {
  super(props)
}
```
is not needed in the class version, so the comparison is really 23 vs 21 lines :)

That critique aside it does seem to make sense to change the components under `series/XXXSeries` and `tooltip/XXXTooltip`. The file size would be reduced

It would however not work for the `interactive/*` because some of them are stateful,

the components under `/interactive/components/*.js` are stateless, so for e.g. https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/components/GannFan.js

even though it is stateless, modifying this as a Stateless Functional Component in my view will not necessarily make it improved, the `render` method would be too long.

Aside from that I use [this](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) extension in vscode, to look at the outline of a file,

![deepinscreenshot_select-area_20171213210907](https://user-images.githubusercontent.com/10691183/33973722-eff98924-e049-11e7-86e7-1d48f22de84c.png)

it gives a clear distinction between variables inside the `render` function and class level methods, and I find that very helpful, making everything inside the `render` would be - in my subjective view - difficult to navigate the file.

This pattern is a nice fit for smaller components, but once the components get bigger and have multiple functions to be declared inside the `render` method, it becomes harder to use.

Having said that, I feel the XXXSeries and XXXTooltip would benefit from this approach and I will keep that in mind for future new series/tooltips I will add

**Comment by piotryordanov** [comment]
I use stateless only components, but not because it reduces the number of lines of code, but because it forces the habit of making everything into small functions, avoiding source code files that inflate in size over time, making them a pain to maintain and look at.

As an example using Ramda, here is how I compute the indicators:

```
  R.pipe(
    R.filter((item) => item.date = new Date(item.date)), // eslint-disable-line
    getMACD(),
    getRSI(),
    getSTO(),
    getEMA(10),
    getEMA(20),
    getEMA(50),
    getEMA(100),
    bb,
  )(initialData)
```

Where `getEMA` is : 
```
const getEMA = (period) =>
  ema()
    .options({ windowSize: period})
    .merge((d, c) => { d['ema' + period] = c; })
    .accessor(d => d['ema' + period]);
```

(Same goes for the other functions) 

Compared to the example in the source code:
```
const calculatedData = smaVolume50(macdCalculator(ema12(ema26(initialData))));
```

- - - -

I like this VS Studio plugin you are using. What exactly is it showing u there? I use vim, so I'm wondering if that is similar to ctags!

**Comment by rrag** [comment]
unrelated, but you can calculate the indicators differently,

in your e.g. you have 8 indicators

```js
    getMACD(),
    getRSI(),
    getSTO(),
    getEMA(10),
    getEMA(20),
    getEMA(50),
    getEMA(100),
    bb,
```

and each of these is merging the entire data with the indicator 8 times,  My suggestion is to calculate just the indicators separately, like

```js
const ema10Algorithm = ema().options({ ... })
const ema20Algorithm = ema().options({ ... })
const ema50Algorithm = ema().options({ ... })
const ema100Algorithm = ema().options({ ... })
const macdAlgorithm = macd().options({ ... })
const rsiAlgorithm = rsi().options({ ... })
const stoAlgorithm = sto().options({ ... })
const bbAlgorithm = bollingerband().options({ ... })

const indicatorData = {
  ema10: ema10Algorithm(data),
  ema20: ema20Algorithm(data),
  ...
  ...
}
```
you will find that indicatorData does not contain the ohlcv but just the indicator values
you can merge that with the data, using a zip or other techniques,

the important thing to note here is that they come from `react-stockcharts/lib/calculator` and not `react-stockcharts/lib/indicator` like so
```js
const {
	ema,
	bollingerband,
	macd,
	rsi,
	sto,
} = require("react-stockcharts/lib/calculator")
```

About the stateless components, I agree with your view 

The VS Code plugin shows the outline of the file, like https://github.com/Microsoft/vscode/issues/5605#issuecomment-241707033 in eclipse I dont know about ctags, and vim!!!! if only I know how to exit it ;)
