### ISSUE TITLE
HoverTooltip with Annotate problem

### ISSUE THREAD

**Issue by mixtale** [rrag/react-stockcharts#424]
when I use HoverTooltip with Annotate,
Annotate text is always over tooltip box.
I know this problem is because tooltip drawn on canvas but annotate is drawn by svg.
can I fix this z-index problem?

you can check this issue when you use HoverTooltip in MovingAverageCrossOver example too.

**Comment by rrag** [comment]
this cannot be fixed by z-index since svg is always on top of canvas. The only solution I have here is to create a new custom component which will draw things on canvas instead.

The `Annotate` component was written before all the recent interactive indicators were developed, so there is a lot that can be done based on the examples of interactive indicators. Please feel free to dig in and create custom components that draw on canvas

**Comment by cbrwizard** [comment]
Using `LabelAnnotation` component instead of `Annotation` helped me

**Comment by alexbom** [comment]
> Using `LabelAnnotation` component instead of `Annotation` helped me

@cbrwizard Could you give an example, please? I've meet same problem.
My annotation looks like this, but still staying above tooltips.

`
            <Annotate
              with={LabelAnnotation}
              when={d => this.computeAnnotation(d) === actionStateNames.short}
              usingProps={short}
            />
`
