### ISSUE TITLE
Set Chart initial zoom level?

### ISSUE THREAD

**Issue by Ejnot** [rrag/react-stockcharts#490]
First of all thanks for this awesome chart library.

I just have a question, so i have a series of data in minute i successfully displayed the chart was displaying the whole series of data this is what it looks when it doesn't have xExtents: 
![image](https://user-images.githubusercontent.com/25398663/37277937-27f809d2-2621-11e8-9b11-f2fb111e49c8.png)

then this is what it looks when it has xExtents:
![image](https://user-images.githubusercontent.com/25398663/37277964-3bd83850-2621-11e8-8d58-b38e89c33090.png)

I removed xExtents because i am updating the data and it causes chart to reset the view when the data is updated for example im moving over the chart using pan and zooming in and out but when data is updated it resets to the original view and it fixes when i remove xextents but the problem now is the data is forcing to display the whole series and its doesn't look candles anymore.

Do you think what i need is to control the initial zoom level? or do i need to modify something else to achieve the 1min interval view in xAxis while updating data. btw the data comes in websocket. 

Thanks again!

**Comment by rrag** [comment]
You are on the right path, setting `xExtents` is how you can control the initial left and right coordinates and thus the level of zoom.

What you might be doing wrong is setting 

```jsx
<ChartCanvas xExtents={[left, right]} ...>
  ...
</ChartCanvas>
```

This would create a new array of length 2 every time your component is rendered, and since `xExtents` changed the chart with reset to the new values. You have to make sure the created `xExtents` is the same across render invocations.

Setting `xExtents` in the component state or a redux style store high up will solve this. I have done the same thing in the [demo](https://demo.reactstockcharts.org/) the initial `xExtents` is set tot he last 200 candles and then never changed till you do one of

- press the reset button on the zoom button
- Change the ticker
- Change from simple to advanced charts
- Change interval (1m, 15m, 1d, 1wk etc)

let me know how that works when you try it

**Comment by ndaybreak** [comment]
the demo is closed ?

**Comment by otsybulsky** [comment]
open this demo https://github.com/rrag/react-stockcharts/issues/490#issuecomment-375931938 please

**Comment by srhtylmz19** [comment]
any update ?
