### ISSUE TITLE
STO customization

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#516]
I'm interested in having similar customization to the STO as we have had for the RSI. The 2 points I think of are the following:

1. Ability to change the boundary lines (overbought/sold) `DashTypeArray`.
2. Ability to change colors of line when it is above/below the boundary lines.

I can help with making the first one since it's similar to what I did to the RSI. 
However, I did not work on splitting the RSI myself. Is it hard, or is it possible to clone the functionality into the STO from the RSI?

**Comment by rrag** [comment]
The trick to getting 2 different colors for the same path above/below a threshold is to use 2 paths with different colors and clip them differently

so
path1 with color1 can be clipped so it shows only between 20-80
path2 with color2 can be clipped so it shows only outside 20-80

the problem is that clip in svg is achieved by using a `def` and adding a `clip-path` style to the path. for canvas it is using the `ctx.clip();` 

this should help you understand what is going on in the `RSISeries.js` Let me know if you have any questions. Good luck with adding STO with this feature
