### ISSUE TITLE
Help - Integrating live chart on my website

### ISSUE THREAD

**Issue by ac647** [rrag/react-stockcharts#579]
Hello

I require someone to help me put this live candlestick chart on my website? in real time please. I have the live running crypto data api

**Comment by rrag** [comment]
Hi @ac647 appears you are looking to hire someone? Unfortunately this is not a job board, and used to track issues and feature requests for the library.

If there is a specific problem you are facing I am happy to help when I get some time. Since this issue is too broad and not actionable I am going to have to close it
