### ISSUE TITLE
Question: Generic Chart Types

### ISSUE THREAD

**Issue by aajtodd** [rrag/react-stockcharts#7]
This project is awesome, great work!

Just wanted to ask a few questions.
It appears (and I could be wrong) on each of the examples the data is assumed to have open/high/low/close information.

1. How would you handle plotting just an equity curve without for example open/high/low/close? In other words a standard line series (e.g. http://www.highcharts.com/stock/demo/basic-line). I currently use highcharts/highstock for this but the panning/zooming and crosshair capabilities are of interest.  

2. Is there support for a max drawdown chart type? If not would you just use the area chart?

Would love to see additional documentation on how all the components connect/work together. On your roadmap you mark some of that so perhaps it's coming. Again awesome stuff!

**Comment by rrag** [comment]
Thank you for the kind words,

#1.
you can do that with [area chart](http://rrag.github.io/react-stockcharts/documentation.html#/area_chart)  change the series from `AreaSeries` to `LineSeries` if you prefer. The important thing to look for is the `yAccessor` on `DataSeries`. Look at the [stockscale](http://rrag.github.io/react-stockcharts/documentation.html#/candlestick_chart) example. you could swap out the `CandlestickSeries` with a `LineSeries`/`AreaSeries` and also change the `yAccessor` to `d => d.close`

#2. 
Drawdown chart type seems to be a variation of Area/Line where the base of the y axis is at the top instead of bottom. I think it should be possible, but will have to try it out, May be needs some tweaks to make it happen.

The most important feature I have been trying to achieve is composable charts, so if you don't like a certain part that can be swapped out with your custom component. There is some documentation which is needed to explain how that can be done. Still on the roadmap. Is there anything you are looking for which is not in the Documentation section of the [coming soon](http://rrag.github.io/react-stockcharts/documentation.html#/coming_soon...) page? I would like to reduce the barrier to entry.

**Comment by rrag** [comment]
Reading more on Drawdown, it is a derived field. So it would have to be an indicator which will calculate the drawdown, and may be we can reuse the Area/Line to plot it.

**Comment by aajtodd** [comment]
Thanks for the quick answers.

1. Makes sense, I like the abstraction.
2. Yup, it's usually just an area chart or line series.
 * I think having the option to supply the drawdown series directly is fine. I would think just trying to draw an area/line chart might actually work already. The yAxis doesn't have to necessarily be at the top (if you end up implementing it I would make it as a change to configure where the y-axis is which could be used on other charts for instance)
 * Perhaps down the road add an indicator to take care of converting a returns series to a drawdown series or something.

Nothing missing in particular in the documentation. Obviously lowering barrier to entry is a good thing and sounds like you are working on additional documentation already.

It appears you are well on the way to composable charts! I stumbled on this as I'm starting to learn react. If I end up using this I will certainly try to give feedback, help with documentation, etc. I know of d3 but never used it so might not be a lot of help though.

I've got a lot on my plate currently and don't know when I'll get around to this, will be watching though. 
Again awesome stuff!

**Comment by aajtodd** [comment]
Also in case you wanted to explore drawdown and know a little python/pandas this code should convert a price or cumulative performance series to a drawdown series.

```python
import pandas as pd

def max_dd_series(series, pct=True):
    """
    Calculate the maximum drawdown series/vector. Use max_dd to calculate
    the absolute minimum drawdown of the entire series as a scalar.
    :param series: pandas series of values
    :param pct: boolean flag, if set return the series as percent drop. Set
                to false to return drawdown value from previous high.
    :return: Series of drawdowns in either percent or absolute value
    """
    max2here = pd.expanding_max(series)
    dd2here = series - max2here
    # dd2here gives drawdown as value to get max_dd series
    # in percent drop:
    #  ((max2here + dd2here) / max2here ) - 1
    #
    # this works because dd2here is negative and calculated from the peaks
    # which means max2here + dd2here gives the value / some peak. Dividing
    # by the peak gives the percentage of point (e.g. 0.96).
    # Subtract 1 to get the percentage drop

    dd2here_pct = ((max2here + dd2here) / max2here) - 1
    if not pct:
        return dd2here
    else:
        return dd2here_pct
```

**Comment by rrag** [comment]
Thank you,
I will add a this in the roadmap for `v0.3`. I think it will be a good addition with the volume profile chart, which is also planned for `v0.3`

**Comment by rrag** [comment]
Added to the roadmap

**Comment by rrag** [comment]
added documentation on creating custom Series components and custom indicators

http://rrag.github.io/react-stockcharts/documentation.html#/custom_create_indicator
http://rrag.github.io/react-stockcharts/documentation.html#/custom_create_xxxseries

Appreceate feedback

**Comment by nurettinakpolat** [comment]
Can't find any documentation about creating custom indicator or custom_create_xxxseries at the location above
