### ISSUE TITLE
[Help needed] non-bijective functions drawing

### ISSUE THREAD

**Issue by Pinxie** [rrag/react-stockcharts#76]
Hello,

I can have curves which possess 2 Y values for the same X. for example :

![plotnoninjective](https://cloud.githubusercontent.com/assets/15984761/15329447/15e4b1c4-1c59-11e6-9f1d-63358dd24cda.png)

Is it at all possible to do this kind of thing with react-stockcharts ?

If not, is there for me any way to do it without breaking everything? I didn't upgrade react-stockcharts yet since 6 months ago... is the fact that data must be sorted by X still a prerequisite?

**Comment by rrag** [comment]
Interesting problem, 

The sorted x value is needed as 

1. binary search is used to get the nearest mouse item
1. on zoom, binary search is used to find the left and right
1. on pan, binary search is used to find the left and right

and binary search needs sorted data for it to work.

Since you might not have upgraded to 0.4, the `xExtents` and `yExtents` accept a function too, so you have more control on the data being shown

would it be possible for you to draw this as 2 lines, with each row as
```
{ x, y1, y2}
```

If you can upload a sample dataset you are working with, I would like to see if there are other issues.

**Comment by Pinxie** [comment]
Here is, I think, a representative example of data:

[sampleData.xlsx](https://github.com/rrag/react-stockcharts/files/270365/sampleData.xlsx)

With a beautifuly hand drawn associated Plot that draws (X, Y) (part of it)

![plotdatadraw](https://cloud.githubusercontent.com/assets/15984761/15357582/0531f8f8-1d00-11e6-94bc-ed203a013b90.png)

the sorted Date column only indicates the order in which the data points should be joined.

I feel I can't draw this kind of thing as N number of lines, because there could be a ton of lines (here my sample data is relatively simple so I can draw it easily, but imagine the X column was { 0, 1}, there would be around 14000 lines (two for each back and forth)

And yes, I would need quadratic bézier, but I think I saw it would not be a problem.

**Comment by rrag** [comment]
There is no plan as of no to implement something like this, closing this now
