### ISSUE TITLE
Limited Pan and Zoom

### ISSUE THREAD

**Issue by cesardeazevedo** [rrag/react-stockcharts#80]
How to limit zoom and pan? I've a very sensitive mouse (magic mouse), and a little wheel touched it scrolls everything, showing like a very big ticker on the screen, i didn't tested with others mouses though, i would like to limit zoom and pan at some point range.

I'm almost pretty sure that you did it on the main [demo example](http://rrag.github.io/stockcharts-demo/), but i only found the [compiled version](https://github.com/rrag/rrag.github.io/tree/master/stockcharts-demo) of it, (which i was also very interested at the logic behind the periods 10d, 1m, 5m, 10m), i also didn't find anything related on the API, and not sure if is related to the pan action callback #51 

Thanks in advance.

**Comment by rrag** [comment]
This is not configurable via a prop now.

On the `next` branch the zoom can be controlled by modifying this line

https://github.com/rrag/react-stockcharts/blob/next/src/lib/scale/evaluator.js#L95

```diff
- return arrayLength < width * threshold && arrayLength > 1;
+ return arrayLength < width * threshold && arrayLength > 20;
```

Change the min number of points to show from 2 to 21,

**Comment by cesardeazevedo** [comment]
Cool, it works, should be this value on a prop in a future versions?

But what about zoom out, there's a way to avoid chart get like this?
![screen shot 2016-05-25 at 02 46 04](https://cloud.githubusercontent.com/assets/5366959/15529750/e64ac200-2225-11e6-82ec-1464817b67c5.png)

**Comment by rrag** [comment]
> Cool, it works, should be this value on a prop in a future versions?

Yeah it should be a prop with a default value of 1.

> But what about zoom out, there's a way to avoid chart get like this?

this also has to be addressed in the `canShowTheseManyPeriods`, but I am not entirely sure what the right solution is. do you have any suggestions?

**Comment by rsklyar** [comment]
![screen shot 2016-07-01 at 20 04 05](https://cloud.githubusercontent.com/assets/6270599/16528697/1926fd42-3fc7-11e6-974b-8a318dcb3b30.png)

zoom issue (

**Comment by cesardeazevedo** [comment]
@rsklyar I'm not sure what's going on your chart, but it seems a data issue instead of the zoom itself, are you passing a regular data to your chart? i suggest that you try a test with [MSFT_full.tsv](https://github.com/rrag/react-stockcharts/blob/master/docs/data/MSFT_full.tsv) file, otherwise we'll need more information on what is going on.

@rrag Sorry to disappear for a while, i've been working a lot on others stuff. The zoom issue is more complex than a thought, i thought that was something related on the EventHandler, but it's more tied on TimeScale, and it's complex, even more now with the new discontinuousTimeScaleProvider.js, i'm not sure if the new timescale is ready, but main point is, how to get a nicer visualization period without messed it up, the scroll is too much sensitive and there's no way to limit the time scale.
So i got some references about these issues, on [tradingview](https://www.tradingview.com/chart/zt9KvJYy/) even tough you can easily move your chart freely, it doesn't have a sensitive zoom, for instance, i've to do a long scroll with my finger at least 3 times to reach the max scale, also [cryptowat](https://cryptowat.ch/bitfinex/btcusd/1d) does a nice job limiting the zoom scale.

I will plan to take some time to debug it, and understand how it works, keep doing awesome work.

Thank you.

**Comment by rrag** [comment]
@cesardeazevedo the new scale is complete, I am happy with the output so far. It spaces out the ticks pretty well, and the spacing does not get messed up on pan towards the end.

about the zoom. the big difference between tradingview and here is that the midpoint of the zoom in trading view is always the last candle on the viewport, while in react-stockcharts, it is the closest candle to the mouse cursor. This makes the zoom go in both directions. Also the zoom calculation is an over simplification of what `d3.zoom.behavior`. The more you zoom the faster it gets. I understand the sensitivity is a concern when using a trackpad. if you try it with a mouse I think it feels right.

Try the zoom on the below using mouse and trackpad
http://plnkr.co/edit/pTCRj8StLntWYXwIyXIM?p=preview
this is a slightly modified version of http://bl.ocks.org/mbostock/3681006

source:
http://stackoverflow.com/questions/12310024/fast-and-responsive-interactive-charts-graphs-svg-canvas-other

The responsiveness is because when you zoom in the domain is halved, and zoom out means you double the domain. that can be controlled in 

https://github.com/rrag/react-stockcharts/blob/next/src/lib/EventHandler.js#L418

try to play with the values 2 (has to be more than 1) and 0.5 (this has to be less than 1) there and see what suits best. I am open to changing the default values, even make that configurable.

**Comment by rrag** [comment]
@cesardeazevedo would you willing to help me out with this one.

change the values on

https://github.com/rrag/react-stockcharts/blob/next/src/lib/ChartCanvas.jsx#L426

and let me know what works best for you

**Comment by rrag** [comment]
merged to master and `0.6.0-beta.2` published to npm

**Comment by cesardeazevedo** [comment]
Thank you rrag, [this commit](https://github.com/rrag/react-stockcharts/commit/1f346ad03ba19714d85566290325189a3df2049a) also helped a lot.

**Comment by srhtylmz19** [comment]
@cesardeazevedo @rrag didnt get the result ? how to limit pan and zoom ?

**Comment by khaphannm** [comment]
same problem here, how to limit the pan ?
