### ISSUE TITLE
Help on the demo

### ISSUE THREAD

**Issue by debsush** [rrag/react-stockcharts#87]
Hi,

I would like to know the source code used to create the demo

**A demo built with react-stockcharts**

I would like to build a similar chart cum layout (supporting multiple charts) and build a wrapper around that exact source code in R.  Was wondering if you could point me to the JS code behind this amazing demo.

Thank you and cheers to this amazing library

Regards,
SD

**Comment by rrag** [comment]
I am sorry, the demo is not opensource.

**Comment by debsush** [comment]
Noted. Thank you. Would appreciate an example where we can add an
externally computed technical indicator as a series to the chart.

**Comment by rrag** [comment]
it does not really matter if an indicator is calculated externally or not, say you have the indicator pre calculated then you would have data as

```
date, close, indicatorA, indicatorB
..., ..., ..., ...
..., ..., ..., ...
..., ..., ..., ...
```

you would create a chart like this

```jsx
<ChartCanvas ...
        data={data}
        xAccessor={d => d.date} ...>
    <Chart id={1}
            yExtents={d => [d.close, d.indicatorA, d.indicatorB]} ... >
        <LineSeries yAccessor={d => d.close}/>
        <LineSeries yAccessor={d => d.indicatorA}/>
        <LineSeries yAccessor={d => d.indicatorB}/>
    </Chart>
    ...
</ChartCanvas>
```

This is assuming the indicator is a line, if you have a complex indicator something like MACD, or BollingerBand, you would need to create a custom Series to plot that.

**Comment by debsush** [comment]
Thank you

**Comment by rrag** [comment]
You are right. why do you want to calculate the indicator externally? Is there a problem in creating a calculator which calculates the indicator values, as part of the lifecyle?

**Comment by debsush** [comment]
Actually,  the library currently covers only 8-10 indicators and I am interested in providing my users around 60 indicators which I can build using R.  So while R will be used for computing, your JS library can be leveraged for charting.  

To your point, how can I build a calculator which builds the indicator values as part of the lifecyle?  I am more of a R guy than a Java guy and would appreciate your guidance.

Also, I will be more than happy to provide those additional indicator algorithms over to you but it will be in R script.

Regards,
SD

**Comment by rrag** [comment]
I see. your indicators in R, are they pre built? or you will be creating them fresh.

In my mind the best solution would be to create these indicators in javascript, because not all indicators are the same, many of them are oscillators, they include not just lines, but also a combination of area and bar and discontinuous lines (Parabolic SAR). Some just change the background of the chart. So even if you have indicator calculation in R, you are still dependent on javascript to draw that on the chart.

That said I understand the limitation on the knowledge of javascript and R.

Since it seems you can invoke javascript from R. and you would probably want to use a combination of indicators, some from javascript and some from R, I suggest you do the following.

```
var macdCalculator = macd()
    .fast(12)
    .slow(26)
    .signal(9)
    .merge((d, c) => {d.macd = c})
    .accessor(d => d.macd);

var dataWithIndicatorsCalculated = anotherCalculator(macdCalculator(data));
```

you can simply compose the calculators together. Since you will be pre-calculating the indicators do not send them to `ChartCanvas`

```diff
<ChartCanvas width={width} height={750}
    margin={margin} type={type}
    seriesName="MSFT"
-   data={data} calculator={[ema20, ema50, slowSTO, fastSTO, fullSTO]}
    ... >
```

Calculating all the indicators is quite fast, so I suggest you do that in the `render` method of your react component

Does this make sense?

It would be great if you can share a few of the indicators in R, I have no knowledge of R currently, I can try my hand at converting them to javascript. I do have plans to add more indicators

http://rrag.github.io/react-stockcharts-next/documentation.html#/coming_soon...

I also want to point you to this another amazing library [d3fc](https://d3fc.io/components/series/candlestick.html) the indicators on react-stockcharts are inspired by d3fc indicators, if these new indicators are in javascript d3fc can also benefit from it.

**Comment by timelyportfolio** [comment]
@debsush see http://www.buildingwidgets.com/blog/2015/9/10/week-36-stockchartr for a very thin wrapper that I wrote last year.

**Comment by debsush** [comment]
Wow!! Now I got ragu and Kent in the same forum - its a dream combo.....

@rrag  Let me give your approach a try.  I will send them over to you (please provide your email)

@timelyportfolio :  Kent I would like to build on your initial work so that it is current with the latest version.  I will email you separately to kickstart this project on my part and seek your guidance from time-to-time .  What would be really mouth watering is to have TTR/Quantmod integrate in your wrapper.  I will be more than happy to work under your mentorship to get this going.

Regards,
SD

**Comment by timelyportfolio** [comment]
@debsush I would enjoy working with you on this.  There is an ongoing Google Summer of Code (GSOC) project that will address `chartSeries`, so I would prefer to wait until we get more clarity (maybe a couple of weeks) on this before staring work on a more full-featured htmlwidget wrapper.  Would that be ok?

**Comment by debsush** [comment]
@timelyportfolio 

I am eagerly waiting for that release as discussed earlier.  I think you are closer to that project than I am and will appreciate if you could let me know on its release.

I would also like to point that the GSOC project may not cover the following features available in reactstockchart

1. Chat Types:  Kagi, Renko etc.
2. Interactive drawing tools like fibonacci retrenchment.
3. Advanced features like volume profile.

So I understand and agree to your point.  We can keep the above in our TODO list

**Comment by rrag** [comment]
Thanks @timelyportfolio for the nice article
